### ISSUE TITLE
No detected result when I change input image size to 768X448

### ISSUE THREAD

**Issue by Amalle** [duangenquan/YoloV2NCS#10]
Hi @duangenquan 
I trained a model with tiny-yolo-voc.cfg(changing input image size to 768X448).
> [net]
batch=64
subdivisions=8
width=768
height=448
channels=3
momentum=0.9
decay=0.0005
angle=0
saturation = 1.5
exposure = 1.5
hue=.1

Compiling and runing is ok with NCS, but there is no detected result. Changing to 416X416, the results is coming out.

**Comment by duangenquan** [comment]
Could you try to set input size as 768x768, or 448x448?

**Comment by Amalle** [comment]
448x448 is ok. But 768x768 can not work.

**Comment by duangenquan** [comment]
Is 768x768 too large?

**Comment by Amalle** [comment]
Setting input size as 768x768 get this:

> Traceback (most recent call last):
  File "./detectionExample/Main.py", line 30, in <module>
    results = detector.Detect(img)
  File "/home/mq/maqiao/YoloV2NCS/detectionExample/ObjectWrapper.py", line 90, in Detect
    out, userobj = ObjectWrapper.graphHandle[0].GetResult()
  File "/usr/local/lib/python3.5/dist-packages/mvnc/mvncapi.py", line 264, in GetResult
    raise Exception(Status(status))
Exception: mvncStatus.MYRIAD_ERROR

**Comment by duangenquan** [comment]
I guess 768x768 costs too much memory in GPU. :)

**Comment by duangenquan** [comment]
If you want to make 768x448 working, you might need to carefully add some pads in some layers during model conversion. But this might not be easy to maintain. Could you describe why you want to use 768x448 as input?

**Comment by Amalle** [comment]
All my training images are 1920x1280. So, I changed input size to 768x448.

**Comment by duangenquan** [comment]
It will be better to use similar aspect ratios for training and testing (if you set RANDOM as 1 during training).
In yolov2, if you set the input size in training configuration 448x448, it will resize any images properly and may add some padding pixels.

**Comment by Amalle** [comment]
@duangenquan Thanks for help
