### ISSUE TITLE
error: invalid conversion from ‘long int*’ to ‘Py_ssize_t* {aka int*}’ [-fpermissive]

### ISSUE THREAD

**Issue by imistyrain** [duangenquan/YoloV2NCS#11]
When trying to deploey it on [Raspberry](http://vx2-downloads.raspberrypi.org/raspbian/images/raspbian-2017-12-01/2017-11-29-raspbian-stretch.zip), I got this error:
src/PythonWrapper.cpp:37:66: error: invalid conversion from ‘long int*’ to ‘Py_ssize_t* {aka int*}’ [-fpermissive]
   bool isReadBuffer = !PyObject_AsReadBuffer(obj.ptr(), &buffer, &buflen);

But there is no error on ubuntu16.

**Comment by duangenquan** [comment]
I think movidius stick's library is running in ubuntu16. Could your try to update the OS, or docker?

**Comment by PINTO0309** [comment]
cd YoloV2NCS
$ nano ~/YoloV2NCS/src/PythonWrapper.cpp
    //long buflen;
    int buflen;
$ make
